### ISSUE TITLE
JOSS REVIEW: API Docs

### ISSUE THREAD

**Issue by rasbt** [qiime2/q2-sample-classifier#133]
Making further progress on the JOSS review, I was just reading through the docs. I must say that the example/tutorial doc (https://docs.qiime2.org/2018.8/tutorials/sample-classifier/) is awesome, so checking off

> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

is a no-brainer. However, while https://docs.qiime2.org/2018.8/tutorials/sample-classifier/ provides an excellent demo, could you also add an API documentation that lists the available commands and briefly describes what they do as a reference? I.e., to check off the following point

> Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

**Comment by nbokulich** [comment]
thank you @rasbt !

Just to clarify, do you want links to the API documentation added in the tutorials or in the paper? (or both?)

The API documentation exists [here](https://docs.qiime2.org/2018.8/plugins/available/sample-classifier/), and is listed in the [readme](https://github.com/qiime2/q2-sample-classifier#api-documentation). As with the tutorials, it may be ideal to just direct readers to the github repo and provide an updated link to the API documentation from there, just in case the documentation is ever moved.

**Comment by rasbt** [comment]
Ah thanks. Didn't see it down there in the README for some reason. The API docs Look good to me!

> do you want links to the API documentation added in the tutorials or in the paper? (or both?)

It would be nice to have a link from the tutorial to the API docs at least.

Regarding a link in the paper, other JOSS papers also don't reference the API docs explicitly; however, usually the API docs are in a `docs` subfolder which then gets archived with the whole repository upon submission of the JOSS paper. 


Would be nice if @yochannah and @arfon could chime in regarding the JOSS expectations.

**Comment by nbokulich** [comment]
@rasbt thanks! I have added a link from the tutorial to the API reference in [this commit](https://github.com/qiime2/docs/commit/e028ff89a7c784d33e465fe525c8b38fb000e21d). The updated docs will not be published online until the next release of QIIME 2 (now planned for early November)

**Comment by yochannah** [comment]
>Regarding a link in the paper, other JOSS papers also don't reference the API docs explicitly; however, usually the API docs are in a docs subfolder which then gets archived with the whole repository upon submission of the JOSS paper.

@rasbt I've had a word with the other editors - we think the docs are ok as-is. I definitely agree that it's nice to have an archived artifact with docs bundled in, but in this case given the paper/software package is part of a larger pluggable software package, a separate repo just for docs seems quite reasonable.

**Comment by rasbt** [comment]
Awesome, thanks for double-checking!
