### ISSUE TITLE
BUG: confusion matrix class label interval breaks with large sample size

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-sample-classifier#143]
**Bug Description**
Confusion matrix labels get misaligned with very large number of class labels.

This does NOT impact results (e.g., accuracy), only the labels — so plots need to be relabeled, e.g., for publication.

The issue seems to be that the tick intervals are being automatically set, but the tick labels are not being assigned the same interval: https://github.com/qiime2/q2-sample-classifier/blob/master/q2_sample_classifier/visuals.py#L129

**Steps to reproduce the behavior**
Make a confusion matrix with a large number of classes (example below has ~30)

**Expected behavior**
Label interval should match tick interval.

**Screenshots**
![image](https://user-images.githubusercontent.com/1907564/47956548-08b3c680-df74-11e8-90f6-c32caa1f639b.png)

**Comment by thermokarst** [comment]
@nbokulich - @David-Rod, @ebolyen, and I attempted to recreate this issue:

![image](https://user-images.githubusercontent.com/274668/63193073-64da6980-c021-11e9-9255-222e1cacda3a.png)

It _looks_ like the offsetting is no longer a problem (fixed upstream?). Can you confirm that this is the case (and if not, supply us with data that reliably reproduces the issue)? Thanks!

**Comment by nbokulich** [comment]
what are the actual tick labels in your example @thermokarst ?  It looks to me like you are not using a sufficiently large number of classes to trigger this problem (i.e., your tick interval is 1)

**Comment by thermokarst** [comment]
:+1: 

@nbokulich, do you have test data you can share?

Also, I suspect we can do something like [`feature-table heatmap`](https://github.com/qiime2/q2-feature-table/blob/master/q2_feature_table/_heatmap/_visualizer.py#L138-L162) to address the issue.

**Comment by nbokulich** [comment]
Not fixed, check out viz below.

To reproduce:
```
import qiime2
from qiime2.plugins import sample_classifier as sc
import pandas as pd

mdix = [i for i in 'abcdefghijklmnopqrstuvwxyz']
md = pd.Series(mdix, index=pd.Index(mdix, name='sample-id'), name='class')
truth = qiime2.CategoricalMetadataColumn(md)
predictions = qiime2.Artifact.import_data('SampleData[ClassifierPredictions]', md)
cm = sc.actions.confusion_matrix(predictions, truth)
cm.visualization.save('test-matrix.qzv')
```

![image](https://user-images.githubusercontent.com/1907564/63203821-fad4bb00-c046-11e9-843f-aab303c75334.png)
 
Note how the y-axis does not match up. Interestingly, the x-axis appears to have the correct interval + spacing, perhaps that is a clue? 

I have an inkling the issue is in here, we may need to do something like [`ax.get_xticklabels`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.get_xticklabels.html) to grab the correct labels instead of just grabbing all class labels:
https://github.com/qiime2/q2-sample-classifier/blob/2b2c0b5c4a41c95986edeb15557bfac8885dbc77/q2_sample_classifier/visuals.py#L106-L109
