### ISSUE TITLE
confusion-matrix: add parameter for adjusting color scale?

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-sample-classifier#148]
**Improvement Description**
Add parameter (or automatically) adjust scale, e.g., to set colorscale range from 0 to 1

**Current Behavior**
Colors scale to accuracy range, which can be misleading if accuracy rates are consistent across classes.

**Proposed Behavior**
Add a parameter to allow colorscale adjustment, and/or automatically scale colorscale

**Comment by Oddant1** [comment]
Where is the color determined?

**Comment by nbokulich** [comment]
`palette` is a str that determines what colormap to use:
https://github.com/qiime2/q2-sample-classifier/blob/b0ca434a9a6724f375aff54559bac6e8aa01b2a1/q2_sample_classifier/visuals.py#L101-L103

but I don't think that's what you want.

the `sns.heatmap` parameters `vmin` and `vmax` sound like the thing to accomplish adjusting the scale: https://seaborn.pydata.org/generated/seaborn.heatmap.html

I'm not sure we should expose these as separate parameters, though; maybe something like `scale: Str % Choices(['auto', '0to1', '0toMax'])`. What do you think? @thermokarst any thoughts?

**Comment by thermokarst** [comment]
I would personally go the route of matching seaborn, two new params `vmin` & `vmax`, `Float | Str % Choices(['auto'])`.

**Comment by Oddant1** [comment]
Presumably vmin would need to be less than or equal to vmax?

**Comment by nbokulich** [comment]
yes good call @Oddant1

**Comment by Oddant1** [comment]
@thermokarst what would be the expected behavior if they choose auto? Just whatever the plot is right now?

**Comment by nbokulich** [comment]
yes `auto` == do not rescale
