### ISSUE TITLE
BUG: heatmap dimensions are distorted

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-sample-classifier#164]
**Bug Description**
![image](https://user-images.githubusercontent.com/1907564/62170178-2d18b580-b2f0-11e9-8b37-d4f71aa0edfe.png)

**Steps to reproduce the behavior**
generate a heatmap with q2-feature-classifier 2019.7 (older releases were not affected)

**Expected behavior**
heatmap should be square and top/bottom rows should not be truncated.

**Comments**
I am fairly certain this is not isolated to q2-sample-classifier. We should see if q2-feature-table and any other plugins that use `seaborn.heatmap` or `seaborn.clustermap` are affected.

**Comment by ChrisKeefe** [comment]
@nbokulich , does this look right to you? I generated this heatmap after installing matplotlib 3.1.0 to a fresh 2019.7 environment. I did not roll back matplotlib-base, and just wanted to make sure I was getting the expected results before opening a PR to pin this. 
![heatmap](https://user-images.githubusercontent.com/39198770/67340118-9409cd00-f4e1-11e9-804a-117f20475589.png)

**Comment by nbokulich** [comment]
Yes! That looks right. Thanks!

**Comment by thermokarst** [comment]
Hey @ChrisKeefe --- `feature-table heatmap` isn't a good test for this bug, it is built in a different manner that doesn't suffer from the problem [reported above](https://github.com/qiime2/q2-sample-classifier/issues/164#issue-474852259) - can you double check the heatmaps in _this plugin_?

**Comment by ChrisKeefe** [comment]
Thanks for the eyes, @thermokarst . This was built with `sample-classifier heatmap`, which does wrap `feature-table heatmap` but appears impacted in @nbokulich 's [link above](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2019.7%2Fdata%2Ftutorials%2Fpd-mice%2Fsample-classifier-results%2Fheatmap.qzv). 

Maybe I misunderstood the conversation here, but regardless, I generated a clean confusion matrix using the same environment: `19.7`, `matplotlib 3.1.0`(rolled back), and `matplotlib-base 3.1.1` (unmodified). GH is misbehaving right now, but I can slack it to you if you like. 

Does pinning only `matplotlib` feel good to you?

**Comment by thermokarst** [comment]
> This was built with `sample-classifier heatmap`

Thanks for clarifying!

> I was able to generate a clean confusion matrix using the same environment

Perfecto.

> In this context, does pinning only `matplotlib` (and not matplotlib-base) feel good to you?

This seems a little strange to me --- my understanding is that these two packages (`matplotlib` and `matplotlib-base`) should be pinned in lockstep. Did you encounter any issues when you pinned to matplotlib-base 3.1.0?

FWIW - it _looks_ like MPL 3.2 might be [landing any day now](https://github.com/matplotlib/matplotlib/releases/tag/v3.2.0rc1) - maybe we should hold off on making a decision until we get closer to our 2019.10 release day? @ChrisKeefe, do you think you could double-check the confusion matrix results in an env with mpl 3.2.0rc1? Thanks!

**Comment by thermokarst** [comment]
> Hey @ChrisKeefe --- `feature-table heatmap` isn't a good test for this bug, it is built in a different manner that doesn't suffer from the problem [reported above](https://github.com/qiime2/q2-sample-classifier/issues/164#issue-474852259) - can you double check the heatmaps in _this plugin_?

Oops! I was confusing this issue for the issue described in https://github.com/qiime2/q2-sample-classifier/issues/143 --- my mistake! What I wrote [above](https://github.com/qiime2/q2-sample-classifier/issues/164#issuecomment-545424417) holds true, I was barking up the wrong tree regarding the `feature-table heatmap` business. Thanks!

**Comment by ChrisKeefe** [comment]
Downgraded `matplotlib-base` to 3.1.0 in both 19.7 and current dev environments - solving didn't affect any additional libraries, and it produces nice clean heatmaps. 

If matplotlib 3.2 doesn't launch before release, I think we're good to pin both to 3.1.0.
