### ISSUE TITLE
clean up unit tests

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-sample-classifier#167]
**Improvement Description**
The unit tests for this plugin are overgrown. It is time to get organized.

**Current Behavior**
At the time of writing, the unit tests are 1546 lines long. Some cleanup of the code may also improve test runtime.

**Proposed Behavior**
1. split up test_classifier.py into multiple thematic test modules. E.g., types/formats should be tested separately. Visualizations and utilities could also be tested separately.
2. split up or combine some test classes, based on shared test data
3. clean up the test data to simplify tests where possible. E.g., the full-sized datasets could be replaced by toy datasets for more tests
    a. `TestHeatmap` should use toy data, the tests take close to 2 minutes to run for a fairly trivial set of tests.

**Comment by nbokulich** [comment]
Note: @Oddant1 mostly addressed this in #188 

The remaining task is to transition other tests to a toy dataset (e.g., the tests that loop through all estimators could use a toy dataset)... but for now we can wait and see if we still need test runtime shortened. If not, we can close this issue.

**Comment by Oddant1** [comment]
Just wanted to add here in regards to "if test runtime is shortened we can close this issue" test runtime was cut from ~145 seconds to ~70-75 seconds on my machine.

**Comment by Oddant1** [comment]
Are we interested in shortening the test runtime here any further with a toy dataset? I don't really know how to build a toy dataset for this, but test runtime is down from ~145 seconds to ~70-75 seconds.

**Comment by nbokulich** [comment]
hey @Oddant1 — I have heard no more complaints from @thermokarst about these tests holding up busywork.... I am happy to close this issue if @thermokarst is happy with the current test runtime, since I agree at this point we can't expect much more than shaving off many 20 more sec...

**Comment by thermokarst** [comment]
No complaints here, ATM. Just wait, I'm sure I'll come up with somethin...
