### ISSUE TITLE
test failure with sklearn 1.2.1

### ISSUE THREAD

**Issue by emollier** [qiime2/q2-sample-classifier#227]
**Bug Description**
When running against sklearn 1.2.1 in Debian unstable, the test_estimators.py raises AssertionErrors relative to AdaBoostRegressor.

**Steps to reproduce the behavior**
1. Go to q2-sample-classifier source code,
2. run py.test-3
3. scroll back up to the FAILURES pytest paragraph
4. see the two test errors:
```
=================================== FAILURES ===================================
______________ EstimatorsTests.test_train_adaboost_decision_tree _______________

self = <q2_sample_classifier.tests.test_estimators.EstimatorsTests testMethod=test_train_adaboost_decision_tree>

    def test_train_adaboost_decision_tree(self):
        abe = _train_adaboost_base_estimator(
            self.table_chard_fp, self.mdc_chard_fp, 'Region',
            n_estimators=10, n_jobs=1, cv=3, random_state=None,
            parameter_tuning=True, classification=True,
            missing_samples='ignore', base_estimator="DecisionTree")
        self.assertEqual(type(abe.named_steps.est), AdaBoostClassifier)
>       self.assertEqual(type(abe.named_steps.est.base_estimator),
                         DecisionTreeClassifier)
E       AssertionError: <class 'str'> != <class 'sklearn.tree._classes.DecisionTreeClassifier'>

q2_sample_classifier/tests/test_estimators.py:401: AssertionError
_______________ EstimatorsTests.test_train_adaboost_extra_trees ________________

self = <q2_sample_classifier.tests.test_estimators.EstimatorsTests testMethod=test_train_adaboost_extra_trees>

    def test_train_adaboost_extra_trees(self):
        abe = _train_adaboost_base_estimator(
            self.table_chard_fp, self.mdc_chard_fp, 'Region',
            n_estimators=10, n_jobs=1, cv=3, random_state=None,
            parameter_tuning=True, classification=True,
            missing_samples='ignore', base_estimator="ExtraTrees")
        self.assertEqual(type(abe.named_steps.est), AdaBoostClassifier)
>       self.assertEqual(type(abe.named_steps.est.base_estimator),
                         ExtraTreeClassifier)
E       AssertionError: <class 'str'> != <class 'sklearn.tree._classes.ExtraTreeClassifier'>

q2_sample_classifier/tests/test_estimators.py:411: AssertionError
```

**Expected behavior**
I would expect the test suite to pass.

**Computation Environment**
- OS: Debian unstable
- QIIME 2 Release 2023.7.0

**Comments**
1. The test error looks to be caused by the renaming of sklearn AdaBoost _base_estimator_ to plain _estimator_ in version 1.2, see reference 1.
2. I worked around the test failure with the following patch, which you may reuse if you like, but be aware that I haven't ensured it is compatible with earlier sklearn versions:
```patch
--- q2-sample-classifier.orig/q2_sample_classifier/tests/test_estimators.py
+++ q2-sample-classifier/q2_sample_classifier/tests/test_estimators.py
@@ -398,7 +398,7 @@
             parameter_tuning=True, classification=True,
             missing_samples='ignore', base_estimator="DecisionTree")
         self.assertEqual(type(abe.named_steps.est), AdaBoostClassifier)
-        self.assertEqual(type(abe.named_steps.est.base_estimator),
+        self.assertEqual(type(abe.named_steps.est.estimator),
                          DecisionTreeClassifier)
 
     def test_train_adaboost_extra_trees(self):
@@ -408,7 +408,7 @@
             parameter_tuning=True, classification=True,
             missing_samples='ignore', base_estimator="ExtraTrees")
         self.assertEqual(type(abe.named_steps.est), AdaBoostClassifier)
-        self.assertEqual(type(abe.named_steps.est.base_estimator),
+        self.assertEqual(type(abe.named_steps.est.estimator),
                          ExtraTreeClassifier)
 
     # test some invalid inputs/edge cases
```
3. I'm aware I'm probably off specifications with Debian unstable and sklearn 1.2.1; this is mostly a heads up for upcoming versions with a hint on how to resolve the problem at play.

**References**
1. https://scikit-learn.org/1.2/modules/generated/sklearn.ensemble.AdaBoostRegressor.html

Wishing you a nice day,  :)
Étienne.

**Comment by emollier** [comment]
Hi again,

Erm, upon rereading my files, I rediscovered some earlier work of mine from back to February where I had to already [patch a few more invocations of sklearn 1.2], and on which the patch in the description of the issue will depend for a more complete port.  The patch were split because the previous part originally applied to Qiime 2 version 2022.11, and the affected code mentionned in the description might not have existed at that time.

At this point I guess this resembles less of an issue and more of a merge request, but I'm not sure of your expectations on the range of sklearn supported versions, and I'm not necessarily on a rush to push those changes neither.  As I wrote that's mostly a heads up for your information.

[patch a few more invocations of sklearn 1.2]: https://salsa.debian.org/med-team/q2-sample-classifier/-/raw/master/debian/patches/sklearn-1.2.1.patch

With my apologies for the confusion,
Étienne.

**Comment by gregcaporaso** [comment]
Hi @emollier, Thanks for the information on this, and sorry for the slow reply. We have updated our support to sklearn 1.4.2 in the upcoming release of QIIME 2 (2024.5, scheduled for later this month). This does include a fix for this issue that you noticed. You can find installation instructions for the most recent development version of QIIME 2 [here](https://develop.qiime2.org/en/latest/plugins/how-to-guides/set-up-development-environment.html#setup-dev-environment) - the amplicon distribution, listed on that page, would be the one I would recommend installing to get access to the latest version of q2-sample-classifier.

**Comment by emollier** [comment]
Hi Greg,

Greg Caporaso, on 2024-05-16:
> Hi @emollier, Thanks for the information on this, and sorry
> for the slow reply.

Nah, no worries, we're all volunteers here, if things have to
take time, that's okay.  :)

> We have updated our support to sklearn
> 1.4.2 in the upcoming release of QIIME 2 (2024.5, scheduled
> for later this month). This does include a fix for this issue
> that you noticed. You can find installation instructions for
> the most recent development version of QIIME 2
> [here](https://develop.qiime2.org) - the amplicon
> distribution, listed on that page, would be the one I would
> recommend installing to get access to the latest version of
> q2-sample-classifier. 

Thank you for the details, standing by for the upcoming release.

Have a nice day,  :)
Étienne.
