### ISSUE TITLE
`_metadata_to_df` should be replaced with call to get numeric columns from `Metadata`

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-sample-classifier#25]
This method will be added for the 2017.7 release - method name is still TBD.

**Comment by nbokulich** [comment]
@gregcaporaso it doesn't look like `MetadataCategory` has an equivalent call to cast to numeric. `_metadata_to_df` is currently written to handle either `Metadata` or `MetadataCategory` — any suggestions or should I just keep the current function?

I see that there is a new method for `Metadata.filter()` to get numeric columns, but is this something that we need/want to use here?

**Comment by nbokulich** [comment]
Looks like the function `_metadata_to_df` no longer exists. Closing this issue.
