### ISSUE TITLE
README should be ported to a new qiime2 tutorial with release of this plugin

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-sample-classifier#27]
It would be cool if you could use the moving pictures tutorial data to illustrate `classify-samples`, as that would make it really easy to teach this in workshops. The Atacama tutorial data could be useful for `regress-samples` (the `AverageSoilRelativeHumidity` and `pH` metadata columns are the relevant ones), but you might have a better data set for that in which case we could just prep some new tutorial data.

**Comment by nbokulich** [comment]
we have the new tutorial in [this PR](https://github.com/qiime2/docs/pull/183)

is there any need to copy that tutorial into this repo, or is the original tutorial sufficient?
