### ISSUE TITLE
add options to pickle/output estimators

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-sample-classifier#4]
will require QIIME2 pipelines to allow output of visualization and artifact (pickled estimator) in a single action.

However, in mean time could prototype with a `fit_model` method.

**Comment by mortonjt** [comment]
This one you will need to be careful with, since pickle breaks for large files.
If the pickled models are small, it may not be an issue.

**Comment by nbokulich** [comment]
in discussion with @BenKaehler we need to use `Pipelines` in place of estimators, and `HashVectorizer` to vectorize feature IDs

**Comment by nbokulich** [comment]
fixed in #101
