### ISSUE TITLE
BUG: confusion matrix reverse y-axis

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-sample-classifier#50]
this has only happened once and usually works, but it has happened:

![image](https://user-images.githubusercontent.com/1907564/29148478-3d438e20-7d33-11e7-9392-c37b28f32ece.png)

**Comment by gregcaporaso** [comment]
I'm still experiencing this issue - sent @nbokulich some info by email.

**Comment by gregcaporaso** [comment]
I confirmed that with seaborn 0.8.0, this bug is fixed by #56.
