### ISSUE TITLE
display important features lists as collapsible blocks of content

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-sample-classifier#61]
Is this even possible if the lists are provided as tables (from pandas DataFrames)?

**Comment by thermokarst** [comment]
@nbokulich, if I am understanding correctly, you want to render a DataFrame to an HTML table, and then be able to collapse it? If so, you are in luck! [q2templates](https://github.com/qiime2/q2templates) uses [Bootstrap](https://getbootstrap.com/docs/3.3/), which includes a simple [collapse widget](https://getbootstrap.com/docs/3.3/javascript/#collapse). This should be pretty straightforward to implement, and I would be more than happy to assist. Thanks!

**Comment by nbokulich** [comment]
awesome, thanks @thermokarst ! That is precisely what I want to do... I should be able to figure that out but will be in touch if I have any questions.
