### ISSUE TITLE
implement neural network models?

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-sample-classifier#7]
**References**
http://scikit-learn.org/stable/modules/neural_networks_supervised.html#neural-networks-supervised

**Comment by valentynbez** [comment]
Nah, neural networks are really bad for tabular data, and in `scikit-learn` only shallow networks are available.
Not worth an effort atm.

**Comment by gregcaporaso** [comment]
We're working through and cleaning up old issues throughout the organization. We're closing this as it's more of a discussion point, and it hasn't had activity in a while. @nbokulich, feel free to re-open as a discussion if you want to get this conversation going.
